"""table restuarent v2

Revision ID: 07ce8b8e1db5
Revises: 5dd3e97429ff
Create Date: 2024-10-23 04:30:29.515222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ce8b8e1db5'
down_revision: Union[str, None] = '5dd3e97429ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('owned_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'restaurant', 'user', ['owned_by'], ['Id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'owned_by')
    # ### end Alembic commands ###
